### ISSUE TITLE
Can't support the latest comfyui?

### ISSUE THREAD

**Issue by huangyan20** [shiimizu/ComfyUI-TiledDiffusion#29] opened 2024-06-20 07:24 UTC
I am unable to use this plugin in the latest comfyui

**Comment by AntiquePass** [comment] 2024-07-05 17:37
Same. I haven't been able to use it for a while in Comfyui. I can't remember when it stopped working, but I has been at least 3 months. 
I've tried to find a way to make it works on my side, bug I'm not too familiar with that and the log isn't giving a lot of information on the issue...

**Comment by cvar66** [comment] 2024-07-10 20:49
Doesn't look like the dev is interested in fixing it. I made a post about it here back in april and the dev marked it closed without even fixing it.

**Comment by AntiquePass** [comment] 2024-07-11 19:50
@huangyan20 I found out the error is caused by the hook_all( ) function ; 'NoneType' object has no attribute 'module_name'.
I tried it and the fix here https://github.com/shiimizu/ComfyUI-TiledDiffusion/pull/26 seems to be working on my side. 
Just download that [utils.py](https://github.com/shiimizu/ComfyUI-TiledDiffusion/blob/14ce31eb37ff3db449336269601a247b1ed56fac/utils.py) file and replace the one in your custom_nodes\ComfyUI-TiledDiffusion.

**Comment by shiimizu** [comment] 2024-07-14 03:23
It should be fixed now.

**Closed by shiimizu** 2024-07-14 03:23 UTC
